renamed allnetx back to astart, but all in one executable

diff --git a/src/abc/Makefile.am b/src/abc/Makefile.am
--- a/src/abc/Makefile.am
+++ b/src/abc/Makefile.am
@@ -26,25 +26,25 @@ abcmoduleslibs += ${DBUS_LIBS}
 endif
 
 LDADD = $(ALLNET_LIBDIR)/liballnet-$(ALLNET_API_VERSION).la
-bin_PROGRAMS = $(ALLNET_BINDIR)/abc
+# bin_PROGRAMS = $(ALLNET_BINDIR)/abc
 lib_LTLIBRARIES = liballnet-abc-@ALLNET_API_VERSION@.la
 liballnet_abc_@ALLNET_API_VERSION@_la_SOURCES = abc.c abc-iface.c abc-iface.h ${abcmodules} ${libincludes}
 liballnet_abc_@ALLNET_API_VERSION@_la_CFLAGS = -DNO_MAIN_FUNCTION -I$(ALLNET_SRCDIR) ${abcmodulesinc}
 liballnet_abc_@ALLNET_API_VERSION@_la_LDFLAGS = -version-info @LDVERSION@ $(ALLNET_LT_LDFLAGS) ${abcmoduleslibs}
 liballnet_abc_@ALLNET_API_VERSION@_la_LIBADD = $(abcmodulelibs) $(ALLNET_LIBDIR)/liballnet-$(ALLNET_API_VERSION).la
-__ALLNET_BINDIR__abc_SOURCES = abc.c abc-iface.c abc-iface.h ${abcmodules} ${libincludes}
-__ALLNET_BINDIR__abc_CFLAGS = -I$(ALLNET_SRCDIR) ${abcmodulesinc}
-__ALLNET_BINDIR__abc_LDFLAGS = ${abcmoduleslibs}
-
-install-exec-hook: 
-	cd $(DESTDIR)$(bindir) && \
-	if [ "$$UID" -eq "0" ]; then \
-		cp abc abc.nosudo && \
-		chown root:root abc && \
-		chmod u+s abc || true; \
-	else \
-		echo "Cannot set suid bit on abc. abc only requires root privileges when using iw."; \
-	fi
-
-uninstall-hook:
-	rm -f $(DESTDIR)$(bindir)/abc.nosudo
+# __ALLNET_BINDIR__abc_SOURCES = abc.c abc-iface.c abc-iface.h ${abcmodules} ${libincludes}
+# __ALLNET_BINDIR__abc_CFLAGS = -I$(ALLNET_SRCDIR) ${abcmodulesinc}
+# __ALLNET_BINDIR__abc_LDFLAGS = ${abcmoduleslibs}
+# 
+# install-exec-hook: 
+# 	cd $(DESTDIR)$(bindir) && \
+# 	if [ "$$UID" -eq "0" ]; then \
+# 		cp abc abc.nosudo && \
+# 		chown root:root abc && \
+# 		chmod u+s abc || true; \
+# 	else \
+# 		echo "Cannot set suid bit on abc. abc only requires root privileges when using iw."; \
+# 	fi
+# 
+# uninstall-hook:
+# 	rm -f $(DESTDIR)$(bindir)/abc.nosudo
